config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :posts
  resources :users, except: [:new]

  root "pages#home"
  get 'about', to: "pages#about"
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
# create login in route, using controller session, and then add the new action to it.

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { in: 6..50}
  validates :description, presence: true, length: { in: 10..300}
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :posts, dependent: :destroy
  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i  
  validates :username, presence: true, length: { in: 3..25 }, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: {case_sensitive: false},format:{with:VALID_EMAIL_REGEX, :multiline => true}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]      
  end 


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = " You mast be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to posts_path if logged_in?
    end
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show  
  end

  def index  
    @posts = Post.paginate(page: params[:page], per_page: 4)

  end

  def new  
    @post = Post.new
  end

  def edit  
  end

  def update  
    if @post.update(post_params)
       flash[:notice] = "Post was updated successfully"
       redirect_to @post
    else
      render "edit"
    end
  
  
    end

  def create  
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post was created successfully"
      # redirect_to post_path(@post)
      redirect_to (@post)
    else
      render "new"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :name)
  end

  def require_same_user
    if current_user != @post.user and !current_user.admin
      flash[:alert] = " You mast be edit or delete your ow article"
      redirect_to post_path
    end

  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  

  def new

  end
  

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user

    else
      flash.now[:alert]="email or password is wrong"
      render "new"
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:notic]= "Logged out"
    redirect_to root_path

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}!!!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated successfully"
      redirect_to user_path
    else
      render "edit"
    end
  end

  def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 4)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notic] = " Account and associated posts have been deleted"
    redirect_to posts_path  
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user 
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin
      flash[:alert] = " You can only edit your own account"
      redirect_to current_user
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size:80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address) 
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"rounded shadow mx-auto d-block")
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
  <div class="container text-center">
  <small>Copyright &copy; <%= link_to "Jie Zhang"  %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">

    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Ruby on Rails 6 App", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Posters", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Posts
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create post", new_post_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Posts", posts_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
     
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete profile", user_path(current_user), method: :delete, class: "dropdown-item text-danger", data: { confirm: "Are you sure?"} %>

          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to "Log in", login_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign up", signup_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails6TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>

<%= link_to "Home Page", root_path %>
<%= link_to "Posts Listing", posts_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center">
      <h1 class="display-4">Learn Ruby on Rails 6</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Learn more</a>
      <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @post %>

  
  <%= form_with(model: @post, local: true, class: "shadow p-3 mb-3 bg-info rounded")  do |f| %>
    <div class="form-group row">
      <%= f.label :title, class:"col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :description, class:"col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_area :description, rows: 10, class:"form-control" %>
      </div>
    </div>
   
    <div class="form-group row justify-content-center">
      <%= f.submit class: "btn btn-outline-light btn-large " %>
    </div>


  <% end %>
  <div class="form-group row justify-content-center ">
    <%= link_to "[ Cancel and return to posts listing page ]", posts_path, class: "text-info" %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="row justify-content-md-center" >
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <% if post.user %>
                <strong> Posted By: </strong> <%= link_to post.user.username, user_path(post.user) %>
              <% end %>
            </div>
            <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-primary" %></h5>
            <p class="card-text"><%= truncate(post.description, length: 100) %></p>

            <button type="button" class="btn btn-outline-primary btn-sm"><%= link_to "View", post_path(post) %></button>
              <% if logged_in? && (post.user == current_user || current_user.admin) %>
                <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Edit", edit_post_path(post) %></button>
                <button type="button" class="btn btn-outline-danger btn-sm"><%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure? "} %></button>  
              <% end %>
            </div>
            <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words( post.created_at) %> ago, edited <%= time_ago_in_words(post.updated_at) %> ago
            </small>
            </div>
        </div>
      </div>

    </div>
  <% end %>

</div>

app/views/posts/edit.html.erb
  <h1 class="text-center mt-4">Edit post</h1>

  <%= render "form" %>

app/views/posts/index.html.erb
<h1 class = "text-center mt-4">Listing all posts</h1>


<div class="flickr_pagination text-center">
    <%= will_paginate @posts, :container => false %>
</div>
<%= render "post" %>

<div class="flickr_pagination text-center mb-4">
    <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/new.html.erb
  <h1 class="text-center mt-4">Create new post</h1>

  <%= render "form" %>

app/views/posts/show.html.erb
<h2 class = "text-center mt-4"><%= @post.title %></h2>

<div class="container">
  <div class="row justify-content-md-center" >
    <div class="col-8 mt-4 ">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            <strong> Posted By: </strong><%= @post.user.username if @post.user %>
            <%= link_to gravatar_for(@post.user, size:50), user_path(@post.user)  %>
        </div>
        <div class="card-body">
            
            <div class="card-text text-left"><%= simple_format(@post.description) %></div>
              <% if logged_in? && (@post.user == current_user || current_user.admin) %>
                <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Edit", edit_post_path(@post) %></button>
                <button type="button" class="btn btn-outline-danger btn-sm"><%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure? "} %></button>  
              <% end %>
            </div>
            <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words( @post.created_at) %> ago, edited <%= time_ago_in_words(@post.updated_at) %> ago</small>
            </div>
    </div>
  </div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?  %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h6 class="alert-heading">The following errors provented the <%= obj.class.name.downcase %> from being saved.</h6>
  <ul>
      <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
        
    <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    
    
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @user %>

  
  <%= form_with(model: @user, local: true, class: "shadow p-3 mb-3 bg-info rounded")  do |f| %>
    <div class="form-group row">
      <%= f.label :username, class:"col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :username, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :email, class:"col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.email_field :email,  class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
    <%= f.label :password, class:"col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.password_field :password, rows: 10, class:"form-control" %>
    </div>
  </div>
   
    <div class="form-group row justify-content-center">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update account" ,  class: "btn btn-outline-light btn-large ") %>
    </div>


  <% end %>
  <div class="form-group row justify-content-center ">
    <%= link_to "[ Cancel and return to posts listing page ]", posts_path, class: "text-info" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class = "text-center mt-4">Listing all posts</h1>
<div class="flickr_pagination text-center">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center" >
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
            <%= link_to user.username, user_path(user)%>
            </div>
            <div class="card-body">
              <h5 class="card-title">
              <%= link_to gravatar_for(user, size:120), user_path(user) %></h5>
              <p class="card-text"><%= pluralize(user.posts.count, "post") %> </p>

              <button type="button" class="btn btn-outline-primary btn-sm"><%= link_to "View profile", user_path(user) %></button>
              <% if logged_in? %>
                <% if user == current_user %>
                  <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Edit profile", edit_user_path(user) %></button>
                <% end %>
                <% if current_user.admin %>
                  <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Delete user", user_path(user), method: :delete,
                  data: {confirm: "Are you sure?"} %></button>
                <% end %>
              <% end%>
              </div>
              <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words( user.created_at) %> ago, edited <%= time_ago_in_words(user.updated_at) %> ago
              </small>
            </div>
        </div>
      </div>

    </div>
  <% end %>
<div class="flickr_pagination text-center mb-4">
  <%= will_paginate @users, :container => false %>
</div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>



<%= gravatar_for @user, size: 150 %>

<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-info" %>
  <% end %>
</div>

<h3 class="text-center mt-4"><%= @user.username %>'s Posts</h3>
<div class="flickr_pagination text-center">
    <%= will_paginate @posts, :container => false %>
</div>
<%= render "posts/post" %>

<div class="flickr_pagination text-center mb-4">
    <%= will_paginate @posts, :container => false %>
</div>